apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "swing-server-"
spec:
  players:
    # set this GameServer's initial player capacity to 10
    initialCapacity: 2
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  template:
    spec:
      containers:
      - name: swing-server
        image: jausseran/swingballserver:latest
        resources:
          requests:
            memory: "4Gi"  # Request 4 GB of memory
            cpu: "2"       # Request 2 vCPUs
          limits:
            memory: "8Gi"  # Limit to 8 GB of memory
            cpu: "4"       # Limit to 4 vCPUs
