apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "swing-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  template:
    spec:
      players:
        # set this GameServer's initial player capacity to 10
        initialCapacity: 2
      containers:
      - name: swing-server
        image: jausseran/swingballserver:latest
        resources:
          requests:
            memory: 128Mi
            cpu: 128m
          limits:
            memory: 1024Mi
            cpu: 512m
