apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "game-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  template:
    spec:
      containers:
      - name: game-server
        image: jausseran/swingballserver
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
